services:
  jupyter:
    build:
      context: .
      dockerfile: ./docker/runtime/Dockerfile.cuda11.0-runtime-ubuntu18.04-py3.8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8888:8888"
      - "8000:8000"
    volumes:
      - ./src:/opt/pysetup/src
      - ./poetry.lock:/opt/pysetup/poetry.lock
      - ./pyproject.toml:/opt/pysetup/pyproject.toml
      - ./notebooks:/opt/pysetup/notebooks
      - ./mkdocs.yml:/opt/pysetup/mkdocs.yml
      - ./docs:/opt/pysetup/docs
      - ./model_repository/:/opt/pysetup/model_repository
      - ./README.md:/opt/pysetup/README.md
  