[tool.poetry]
name = "fastnn"
version = "0.0.1"
description = "A python library and framework for fast neural network computations."
authors = ["Andrew Chang <aychang995@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.4.0"
transformers = "^3.0.0"
jupyter = "^1.0.0"
jupyterlab = "^2.2.9"
wget = "^3.2"
mkdocs = {version = "^1.1.2", optional = true}
mkdocs-material = {version = "^6.1.5", optional = true}
mkautodoc = {version =  "^0.1.0", optional = true}
matplotlib = "^3.3.3"
torchvision = "^0.8.1"
coremltools = "^4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
black = "^20.8b1"

[tool.poetry.extras]
docs = ["mkdocs", "mkdocs-material", "mkautodoc"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
