FROM nvcr.io/nvidia/cuda:12.2.2-devel-ubuntu22.04 as base

LABEL maintainer="Andrew Chang <aychang995@gmail.com>"

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

ENV PYTHONUNBUFFERED=1 \
    # prevents python creating .pyc files
    PYTHONDONTWRITEBYTECODE=1 \
    \
    # pip
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    \
    # poetry
    # https://python-poetry.org/docs/configuration/#using-environment-variables
    POETRY_VERSION=1.6.1 \
    # make poetry install to this location
    POETRY_HOME="/opt/poetry" \
    # don't create poetry venv, we make it ourselves
    POETRY_VIRTUALENVS_CREATE=false \
    # do not ask any interactive question
    POETRY_NO_INTERACTION=1 \
    \
    # paths
    # this is where our requirements + virtual environment will live
    PYSETUP_PATH="/opt/pysetup" \
    VIRTUAL_ENV="/venv"

# prepend poetry and venv to path
ENV PATH="$POETRY_HOME/bin:$VIRTUAL_ENV/bin:$PATH"

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3.10 \
    python3.10-dev \
    python3.10-venv \
    python3-pip \
    curl

# create virtualenv
RUN python3 -m venv $VIRTUAL_ENV

RUN rm -rf /var/lib/apt/lists/*

RUN rm -fr /root/.cache/pip

# install poetry - respects $POETRY_VERSION & $POETRY_HOME
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN poetry config installer.max-workers 10

# copy project requirement files here to ensure they will be cached.
WORKDIR $PYSETUP_PATH
COPY poetry.lock pyproject.toml README.md $PYSETUP_PATH
COPY src ./src

# install runtime deps
RUN poetry install


###########################
#### Development Layer ####
###########################
FROM base as development

ENV FASTAPI_ENV=development
WORKDIR $PYSETUP_PATH

# copy in our built poetry + venv
COPY --from=base $POETRY_HOME $POETRY_HOME
COPY --from=base $PYSETUP_PATH $PYSETUP_PATH

# quicker install as runtime deps are already installed
RUN poetry install --extras "jupyter torch docs"
