FROM python:3.8.12-alpine


#RUN pip install --upgrade pip
#RUN pip install jupyterlab



#CMD ["sh","-c", "jupyter lab --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]