# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: 1.6.1
    - name: Set up Poetry env
      run: poetry env use python3.9
    - name: Config poetry
      env:
        PYPI_FASTNN_TOKEN: ${{ secrets.PYPI_FASTNN_TOKEN }}
      run: poetry config pypi-token.pypi "$PYPI_FASTNN_TOKEN"
    - name: Publish package
      run: poetry publish --build
